name: Admin Cypress Tests

on: [push]

jobs: 
  cypress-run:
    environment: ci
    runs-on: ubuntu-latest
    steps: 
     - name: Checkout
       uses: actions/checkout@v2

     - name: Cache node modules
       env: 
         cache-name: cache-node-modules
         SERVER_URL: ${{ secrets.SERVER_URL }}
         CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
         CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
         NODE_ENV: ci
     - name: print env
       run: |
        echo "the var was detected to be test = " $MYVAR 

     - name: Install client dependencies
       working-directory: admin
       run: npm install

     - name: Create build
       working-directory: admin
       run: npm run build

     - name: Start Admin Frontend in the background
       working-directory: admin
       env: 
         HOST: localhost
         PORT: 3000
       run: npm run start &

     - name: Cypress Component
       working-directory: admin
       run: npm run cypress:ci:component
      
     - name: Cypress e2e
       working-directory: admin
       run: npm run cypress:ci:e2e

     - name: Save screenshots
       uses: actions/upload-artifact@v2
       with:
         name: cypress-screenshots
         path: admin/cypress/screenshots

     - name: Save videos
       uses: actions/upload-artifact@v2
       with:
        name: cypress-videos
        path: admin/cypress/videos


